Fix invalid `ON CLUSTER` clause
This commit fixes the following error,

  java.lang.RuntimeException: com.clickhouse.client.ClickHouseException:
  Code: 62. DB::Exception: Syntax error: failed at position 109 ('ON'):
  ON CLUSTER ******* ENGINE=KeeperMap('/kafka-connect') PRIMARY KEY
  `key`;. Expected one of: storage definition, ENGINE, PARTITION BY,
  PRIMARY KEY, ORDER BY, SAMPLE BY, TTL, EMPTY AS, AS, COMMENT, INTO
  OUTFILE, FORMAT, SETTINGS, end of query. (SYNTAX_ERROR) (version
  24.4.1.2088 (official build))

which is caused by an incorrect placement of `ON CLUSTER` clause.
It should immediately follow the table name.

https://clickhouse.com/docs/en/sql-reference/statements/create/table